apiVersion: v2
name: ottertune-agent
description: "This chart installs the OtterTune Agent into a Kubernetes cluster."
type: application
version: 0.1.4
appVersion: "0.3.10"
icon: https://ottertune.com/favicon.ico
