replicaCount: 1

image:
  repository: "public.ecr.aws/ottertune/agent"
  pullPolicy: "IfNotPresent"


aws:
  # TODO: Write Helper to detect is AccessKey and SecretAccessKey are provided.
  # Either both must be provided or neither must be provided.
  # Add an IF block around their environment variables if they're not
  # provided.
  region: ""
  accessKeyID: ""
  secretAccessKey: ""

# Some of these values are passed into a Configmap and others are stored
# in a secret.
ottertune:
  dbIdentifier: ""
  dbUsername: ""
  dbPassword: ""
  apiKey: ""
  dbKey: ""
  orgID: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  name: ""

# Resources are left blank so they can be a conscious choice for the user.
# This is what Helm recommends because it allows the chart to run on 
# nodes with few resources, like Minikube.
resources: {}
# Allow users to inject their own nodeSelectors, tolerations, 
# affinities, pod annotations, and security contexts.
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
