apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "..serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: "AWS_REGION"
            value: {{ required "Must provide aws.region" .Values.aws.region | quote }}
          {{- if eq (include "..awsCredsEnabled" . ) "true" }}
          - name: "AWS_ACCESS_KEY_ID"
            value: {{ .Values.aws.accessKeyID | quote }}
          - name: "AWS_SECRET_ACCESS_KEY"
            value: {{ .Values.aws.secretAccessKey | quote }}
          {{- end}}
          - name: "OTTERTUNE_DB_IDENTIFIER"
            valueFrom:
              configMapKeyRef:
                name: {{ include "..configmapName" . }}
                key: "db-identifier"
          - name: "OTTERTUNE_DB_USERNAME"
            valueFrom:
              configMapKeyRef:
                name: {{ include "..configmapName" . }}
                key: "db-username"
          - name: "OTTERTUNE_DB_PASSWORD"
            valueFrom:
              configMapKeyRef:
                name: {{ include "..configmapName" . }}
                key: "db-password"
          - name: "OTTERTUNE_API_KEY"
            value: {{ required "Must provide ottertuneAPIKey" .Values.ottertune.apiKey | quote }}
          - name: "OTTERTUNE_DB_KEY"
            valueFrom:
              configMapKeyRef:
                name: {{ include "..configmapName" . }}
                key: "db-key"
          - name: "OTTERTUNE_ORG_ID"
            valueFrom:
              configMapKeyRef:
                name: {{ include "..configmapName" . }}
                key: "org-id"
  {{- if not (empty .Values.serverUrlOverride) }}
          - name: "OTTERTUNE_OVERRIDE_SERVER_URL"
            valueFrom:
              configMapKeyRef:
                name: {{ include "..configmapName" . }}
                key: "server-url"
  {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
