apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ottertune-agent.fullname" . }}
  labels:
    {{- include "ottertune-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ottertune-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ottertune-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ottertune-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: "AWS_REGION"
            value: {{ required "Must provide aws.region" .Values.aws.region | quote }}
          {{- if eq (include "ottertune-agent.awsCredsEnabled" . ) "true" }}
          - name: "AWS_ACCESS_KEY_ID"
            value: {{ .Values.aws.accessKeyID | quote }}
          - name: "AWS_SECRET_ACCESS_KEY"
            value: {{ .Values.aws.secretAccessKey | quote }}
          {{- end}}
          - name: "OTTERTUNE_DB_IDENTIFIER"
            valueFrom:
              configMapKeyRef:
                name: {{ include "ottertune-agent.configmap-name" . | quote }}
                key: "db-identifier"
          - name: "OTTERTUNE_DB_USERNAME"
            valueFrom:
              configMapKeyRef:
                name: {{ include "ottertune-agent.configmap-name" . | quote }}
                key: "db-username"
          - name: "OTTERTUNE_DB_PASSWORD"
            valueFrom:
              configMapKeyRef:
                name: {{ include "ottertune-agent.configmap-name" . | quote }}
                key: "db-password"
          - name: "OTTERTUNE_API_KEY"
            valueFrom:
              secretKeyRef:
                name: {{ include "ottertune-agent.secret-name" . | quote }}
                key: "api-key"
          - name: "OTTERTUNE_DB_KEY"
            valueFrom:
              configMapKeyRef:
                name: {{ include "ottertune-agent.configmap-name" . | quote }}
                key: "db-key"
          - name: "OTTERTUNE_ORG_ID"
            valueFrom:
              configMapKeyRef:
                name: {{ include "ottertune-agent.configmap-name" . | quote }}
                key: "org-id"
  {{- if not (empty .Values.serverUrlOverride) }}
          - name: "OTTERTUNE_OVERRIDE_SERVER_URL"
            valueFrom:
              configMapKeyRef:
                name: {{ include "ottertune-agent.configmap-name" . | quote }}
                key: "server-url"
  {{- end -}}
  {{- if not (empty .Values.ottertune.postgresDBName) }}
          - name: "POSTGRES_OTTERTUNE_DB_NAME"
            valueFrom:
              configMapKeyRef:
                name: {{ include "ottertune-agent.configmap-name" . | quote }}
                key: "postgres-db-name"
  {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
