{{- if not .Values.ottertune.apiKeyExistingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "ottertune-agent.secret-name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  api-key: {{ required "You must provide a value for ottertune.apiKey" .Values.ottertune.apiKey | b64enc | quote }}
{{- end }}
