{{- if not .Values.ottertune.apiKeyExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ottertune-agent.secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ottertune-agent.labels" . | indent 4 }}
type: Opaque
data:
  api-key: {{ required "You must provide a value for ottertune.apiKey" .Values.ottertune.apiKey | b64enc | quote }}
{{- end }}
